Handle cargo publish error on keywords
```
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error: expected at most 5 keywords per crate
```